data: 
    train: 
        path : 'datasets/Messidor/train'
        batch_size : 64
        num_workers : 8
        ratio : 0.3
    val: 
        path : 'datasets/Messidor/valid'
        batch_size : 64
        num_workers : 8
        ratio : 1
    test: 
        path : 'datasets/Messidor/test'
        batch_size : 64
        num_workers : 8
        ratio : 1

optimizer_clf:
  _target_: torch.optim.AdamW
  #lr: 2e-4
  weight_decay: 1e-3
  betas: [0.9, 0.999]
  
optimizer_domain_clf:
  _target_: torch.optim.Adam
  lr: 1e-2
  weight_decay: 1e-5
  betas: [0.9, 0.999]
  
domain_clf:
  _target_: torch.nn.LazyLinear
  out_features : 1
  
seed : 42
hf_model_path : "google/vit-large-patch16-224"
tuned_model_path : "checkpoints/checkpoints_DDR_tune/model_epoch_2_acc_0.815.pth"
ckpt_path : checkpoints/checkpoints_fntn_messidor_only_100_ep
log_path : logs/logs_fntn_messidor_only_100_ep
device : 'cuda'
n_epochs : 150
clf_steps : 9
domain_steps : 4
eval_period : 5